### ISSUE TITLE
custom width sidebar or two different columns

### ISSUE THREAD

**Issue by MrJamsn** [mirucon/coldbox#33]
Hi, first of all, thanks for your grate theme!

I need to display content in a two column layout.
(**left** news ; **right** league tables, upcoming games, etc)

Is there a way to eighter make the sidebar 50% width or to display in the left column different content than in the right one?

thanks!

Br Raffael

**Comment by mirucon** [comment]
Not sure if I understand your question correctly, what you want to do it with this theme is to have the 2 columns with the exact same width for each column? Then you can use the sidebar for one side, and post content for one side. Probably like this stylesheet can help, but it might break something because I could not have the time to test it deeply. You can just try and fix it :)

```css
.right-sidebar-s1 .sidebar-s1 {
  margin-left: -500px;
}

.right-sidebar-s1 .content {
  padding-right: 520px;
}

.sidebar-s1 {
  width: 500px;
}
```
